package de.brainstormsoftworks.taloonerrl.dungeon;

public enum EDungeonSprites {
	NOTHING, FLOOR_ROOM_TOPLEFT_CORNER, FLOOR_ROOM_TOP, FLOOR_ROOM_TOPRIGHT_CORNER, FLOOR_ROOM_LEFT, FLOOR_ROOM_CENTER, FLOOR_ROOM_RIGHT, FLOOR_ROOM_BOTTOMLEFT_CORNER, FLOOR_ROOM_BOTTOM, FLOOR_ROOM_BOTTOMRIGHT_CORNER, WALL_TOPLEFT_CORNER, WALL_TOPRIGHT_CORNER, WALL_BOTTOMLEFT_CORNER, WALL_BOTTOMRIGHT_CORNER, WALL_HORIZONTAL, WALL_VERTICAL
}
