package de.brainstormsoftworks.taloonerrl.dungeon;

public enum EDungeonSprites {
	NOTHING, FLOOR_TOPLEFT_CORNER, FLOOR_TOP, FLOOR_TOPRIGHT_CORNER, FLOOR_LEFT, FLOOR_CENTER, FLOOR_RIGHT, FLOOR_BOTTOMLEFT_CORNER, FLOOR_BOTTOM, FLOOR_BOTTOMRIGHT_CORNER, WALL_TOPLEFT_CORNER, WALL_TOPRIGHT_CORNER, WALL_BOTTOMLEFT_CORNER, WALL_BOTTOMRIGHT_CORNER, WALL_HORIZONTAL, WALL_VERTICAL
}
