package de.brainstormsoftworks.taloonerrl.dungeon;

public enum EFloor {
	NOTHING, ROOM_TOPLEFT_CORNER, ROOM_TOP, ROOM_TOPRIGHT_CORNER, ROOM_LEFT, ROOM_CENTER, ROOM_RIGHT, ROOM_BOTTOMLEFT_CORNER, ROOM_BOTTOM, ROOM_BOTTOMRIGHT_CORNER
}
